### ISSUE TITLE
Cannot runtests after CTRL+C

### ISSUE THREAD

**Issue by msornay** [quantmind/pulsar#163] opened 2015-10-02 14:25 UTC
I'm using Python 3.4 on a Debian Jessie

I'm using a virtualenv

* Run `python -m runtests --coverage`
* Stop it with ctrl+C
* Run `python -m runtests --coverage` again. It fails with the following output :
```
$ python -m runtests --coverage                                               [15-10-02 14:56]
3.4.3 (default, Sep 17 2015, 15:46:34) 
[GCC 4.9.2]
Coverage file available. Type "coverage html" for a report

Bye (exit code = 2)
```

My solution right now is to use `git clean -fdx` between test executions.

**Comment by lsbardel** [comment] 2015-10-10 17:18
That is not great of course, thanks for reporting it.
I cannot reproduce it on a mac os x.
Which OS are you using?

**Comment by lsbardel** [comment] 2015-10-10 20:46
Debian of course :-1:  to me

**Comment by steveholden** [comment] 2016-01-25 22:35
I'm seeing the same issue on Mac OS 10.10.5 - many thanks to @msornay for the workaround

**Comment by steveholden** [comment] 2016-01-26 17:06
The arbiter appears to be calling `stop` with an exception because the pid file is stale. The exception I see is:
```
HaltServer("ERROR. Already running on PID 16308 (or pid file 'test.pid' is stale)",)
```

**Comment by ssbarnea** [comment] 2016-03-14 13:57
Yep, it seems that I raised a duplicate of this at #216

**Comment by lsbardel** [comment] 2016-03-17 08:08
This has been replaced by #218

**Closed by lsbardel** 2016-03-17 08:08 UTC
Labels: bug, moved
